version: "3.8"
services:
  web:
    build: ./app
    ports:
      - "5000:5000"
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - "5432:5432"
